cont

diff --git a/bin/setup_devel_pc b/bin/setup_devel_pc
--- a/bin/setup_devel_pc
+++ b/bin/setup_devel_pc
@@ -1,49 +1,43 @@
 #!/bin/bash
 
-# This script will setup your Devel PC for ezApp development.
-#
-# The sample config settings, found in function config_init, 
-# must first be updated.
-#
+# To get this script (replace 'main' with branch_name)
+# - wget https://raw.githubusercontent.com/sthaid/ezApp/refs/heads/main/bin/setup_devel_pc  
+
+# Before running this script:
+# - user must be member of sudo group
+# - config values must be set, refer to function config_init
+# - path_to_rsa_key_dir must be set to directory containing id_rsa and id_rsa.pub;
+#     this can be ~/.ssh if the rsa key is already present in that directory
+# - path_to_android_tools must be path to android sdk tools zip file;
+#     which can be downloaded from
+#     https://developer.android.com/studio#command-line-tools-only
+# - if git_clone_using_ssh is true then a github account is required, 
+#     and must be configured with the user's id_rsa.pub
+#   ezapp_device should be set to the IP address of your Android device
+#   ezapp_passwd should be set to the ezApp Devel_Password
+#   accept_sdk_license should be set true to automatically accept the sdk license;
+#     set this true only if you understand and accept the Android SDK license conditions
+#   run_build should be set true if you want this script to also build ezApp
+
 # This script performs the following steps:
 # - display and validate the config settings
 # - prompts to continue
-# - copies your provided rsa key to ~/.ssh  (optional)
+# - copies your provided rsa key to ~/.ssh
 # - install and configure git
 # - git clone ezApp
 # - install required linux packages
 # - install android sdk, this creates ~/android/sdk
-# - creates ~/.vimrc  (optional)
-# - create ~/.bashrc_ezapp, and appends a call to this file to ~/.bashrc
-#
-# This script has been tested on
-# - Ubuntu 26.04 LTS running on x86_64
-# - Windows 11 WSL distro Ubuntu-26.04 running on AMD Ryzen 5
+# - creates ~/.vimrc
+# - create ~/.bashrc_ezapp, and adds a call to this from ~/.bashrc
 
-# NOTES:
-# - To get this file replace <branch> with the desired branch, usually 'main'.
-#     wget https://raw.githubusercontent.com/sthaid/ezApp/refs/heads/<branch>/bin/setup_devel_pc  
-#   To run:
-#     chmod 755 setup_devel_pc
-#     ./setup_devel_pc
-#
-# - If git_clone_using_ssh = true
-#       path_to_rsa_key_dir is required,
-#       github account is required, and must be cofigured with the id_rsa.pub
-#   else
-#       path_to_rsa_key_dir is optional,
-#       github account is optional
-#   endif
-#     
-# - Download commandlinetools-linux-nnnnnnnn_latest.zip from here:
-#   https://developer.android.com/studio#command-line-tools-only
-#
-# - The config values, found in fucntion function config_init, are an example.
-#   These config values must be updated for your use case.
-#
-# - If config value create_vimrc is true, this script will create ~/.vimrc with my
-#   preferred settings. The 'tabs' settings will cause tab chars to be replaced 
-#   with space.
+# This script has been tested on
+# - Ubuntu 26.04 LTS
+# - Windows 11 WSL distro Ubuntu-26.04
+
+# To execute this script:
+# - modify config values for your needs
+# - chmod 755 setup_devel_pc
+# - ./setup_devel_pc
 
 # ######## FUNCTION ########
 
@@ -52,30 +46,28 @@ HTTPS_REPO_URL=https://github.com/sthaid/ezApp.git
 
 function config_init()
 {
-    # Notes:
-    # - update these values for your use case.
-    # - avoid using spaces in the paths, that has not been tested.
+    # Note: avoid using spaces in the paths, spaces have not been tested.
 
     if [ "$running_on" = ubuntu_wsl ]; then
         path_to_rsa_key_dir=/mnt/c/Users/STEVEN~1/.ssh
         path_to_android_tools=/mnt/c/Users/STEVEN~1/Downloads/commandlinetools-linux-15859902_latest.zip
-        your_name="Steven Haid"
-        your_email=stevenhaid@gmail.com
-        branch_name=wsl_devel
-        git_clone_using_ssh=true
-        create_vimrc=true
     elif [ "$running_on" = ubuntu_linux ]; then
-        path_to_rsa_key_dir=    # leave this blank because the .ssh dir already has the rsa key files
+        path_to_rsa_key_dir=~/.ssh
         path_to_android_tools=/home/haid/Downloads/commandlinetools-linux-15859902_latest.zip
-        your_name="Steven Haid"
-        your_email=stevenhaid@gmail.com
-        branch_name=wsl_devel
-        git_clone_using_ssh=true
-        create_vimrc=true
     else
         echo "BUG: unexpected value for running_on=$running_on"
         exit 1
     fi
+
+    your_name="Steven Haid"
+    your_email=stevenhaid@gmail.com
+    branch_name=wsl_devel   # xxx temp
+    git_clone_using_ssh=true
+    create_vimrc=true
+    ezapp_device=192.168.1.243
+    ezapp_passwd=secret
+    accept_sdk_licenses=true
+    run_build=true;
 
     echo "Config:"
     echo "- path_to_rsa_key_dir    = $path_to_rsa_key_dir"
@@ -85,11 +77,21 @@ function config_init()
     echo "- branch_name            = $branch_name"
     echo "- git_clone_using_ssh    = $git_clone_using_ssh"
     echo "- create_vimrc           = $create_vimrc"
+    echo "- ezapp_device           = $ezapp_device"
+    echo "- ezapp_passwd           = $ezapp_passwd"
+    echo "- accept_sdk_licenses    = $accept_sdk_licenses"
+    echo "- run_build              = $run_build"
     echo
 
-    # verify if path_to_rsa_key_dir is set that file_id_rsa exists in that dir
-    if [ -n "$path_to_rsa_key_dir" -a ! -f "$path_to_rsa_key_dir"/id_rsa ]; then
-        echo "ERROR $path_to_rsa_key_dir/id_rsa does not exist"
+    # verify user is  member of sudo group
+    if ! id -nG "username" | grep -qw "sudo"; then
+        echo "ERROR user is not member of sudo group"
+        exit 1
+    fi
+
+    # verify path_to_rsa_key_dir exists and contains file id_rsa
+    if [ ! -d "$path_to_rsa_key_dir" -o ! -f "$path_to_rsa_key_dir"/id_rsa]; then
+        echo "ERROR file $path_to_rsa_key_dir/id_rsa does not exist"
         exit 1
     fi
 
@@ -97,14 +99,6 @@ function config_init()
     if [ ! -f "$path_to_android_tools" ]; then
         echo "ERROR $path_to_android_tools does not exist"
         exit 1
-    fi
-
-    # verify that when git_clone_using_ssh is true, that rsa keys are available
-    if [ "$git_clone_using_ssh" = true ]; then
-        if [ ! -f "$path_to_rsa_key_dir"/id_rsa -a ! -f ~/.ssh/id_rsa ]; then
-            echo "ERROR rsa key required when git clone using ssh"
-            exit 1
-        fi
     fi
 
     # verify branch_name is provided
@@ -121,11 +115,6 @@ function config_init()
     if ! git ls-remote --exit-code --heads "$HTTPS_REPO_URL" "refs/heads/${branch_name}" &> /dev/null; then
         echo "ERROR branch $branch_name is not accessible"
         exit 1
-    fi
-
-    # warn if rsa key in .ssh will be replaced
-    if [ "$path_to_rsa_key_dir" -a -f ~/.ssh/id_rsa ]; then
-        echo "Warning: existing ~/.ssh/id_rsa will be replaced"
     fi
 
     # warn that .vimrc will be replaced
@@ -160,9 +149,11 @@ function determine_running_on()
 
 function get_rsa_key()
 {
-    if [ ! -d "$path_to_rsa_key_dir" ]; then
-        echo "ERROR: directory $path_to_rsa_key_dir not found"
-        exit 1
+    # if path_to_rsa_key_dir = ~/.ssh then nothing to do, just return
+    tmp1=$(readlink -f ~/.ssh)
+    tmp2=$(readlink -f "$path_to_rsa_key_dir")
+    if [ "$tmp1" = " $tmp2" ]; then 
+        return
     fi
 
     mkdir -p ~/.ssh
@@ -239,7 +230,7 @@ EOF
 function create_bashrc_ezApp()
 {
 # create ~/.bashrc_ezApp
-cat << 'EOF' > ~/.bashrc_ezApp
+cat << EOF > ~/.bashrc_ezApp
 
 # -----------------------
 # ---- .bashrc_ezApp ----
@@ -272,8 +263,8 @@ export EDITOR=vim
 export GIT_EXTERNAL_DIFF=$HOME/ezApp/bin/git_external_diff
 export ANDROID_HOME=$HOME/android/sdk
 export ANDROID_NDK_ROOT=$ANDROID_HOME/ndk/27.0.12077973
-export EZAPP_DEVICE=192.168.1.243
-export EZAPP_PASSWD=secret
+export EZAPP_DEVICE=$ezapp_device
+export EZAPP_PASSWD=$ezapp_passwd
 export ADB_MDNS=0   # disable MDNS device discovery
 
 # PATH env var
@@ -356,7 +347,7 @@ echo "Installed Linux packages"
 echo
 
 # install android sdk
-ezApp/bin/install_android_sdk $path_to_android_tools
+ezApp/bin/install_android_sdk $path_to_android_tools $accept_sdk_licenses
 echo "Installed android/sdk from $path_to_android_tools"
 echo
 
@@ -371,6 +362,17 @@ fi
 create_bashrc_ezApp
 echo "Created ~/.bashrc_ezApp, and updated .bashrc to call it"
 echo
+
+# build ezApp and ezApp/android
+if [ "$run_build" = true ]; then
+    source ./bashrc_ezApp
+    make -C ~/ezApp
+    echo "Completed make -C ~/ezApp"
+    echo
+    make -C ~/ezApp/android
+    echo "Completed make -C ~/ezApp/android"
+    echo
+fi
 
 # provide final instructions
 if [ "$running_on" = ubuntu_wsl ]; then
