adding support for wsl

diff --git a/android/setup b/android/setup
--- a/android/setup
+++ b/android/setup
@@ -14,6 +14,7 @@ update_build_file()
 
 # ######### MAIN ##########
 
+echo "==== INITIALIZE ===="
 if [ -d SDL ]; then
   read -p "Existing build will be removed, continue (y/n)? " yn
   if [ "$yn" != y ]; then
@@ -23,7 +24,6 @@ if [ -d SDL ]; then
   echo
 fi
 
-echo "==== INITIALIZE ===="
 PACKAGE_NAME=org.sthaid.ezApp
 REPO_TOP=$(git rev-parse --show-toplevel)
 if [ $? -ne 0 ]; then
@@ -33,14 +33,19 @@ ANDROID_TOP=$REPO_TOP/android
 SDL_DIR=$ANDROID_TOP/SDL
 BUILD_DIR=$SDL_DIR/build/$PACKAGE_NAME
 
-cd $ANDROID_TOP
-
 echo "PACKAGE_NAME = $PACKAGE_NAME"
 echo "REPO_TOP     = $REPO_TOP"
 echo "ANDROID_TOP  = $ANDROID_TOP"
 echo "SDL_DIR      = $SDL_DIR"
 echo "BUILD_DIR    = $BUILD_DIR"
 echo
+
+if [[ ! -d $REPO_TOP/src/SDL || ! -d $REPO_TOP/src/SDL_mixer || ! -d $REPO_TOP/src/SDL_ttf ]]; then
+  echo "ABORT: src/SDL directory not found"
+  exit 1
+fi
+
+cd $ANDROID_TOP
 
 echo "==== REMOVE EXISTING ===="
 rm -rf SDL assets setup_files/orig
diff --git a/bin/ezget b/bin/ezget
--- a/bin/ezget
+++ b/bin/ezget
@@ -30,6 +30,10 @@ EOF
 
 # #############  MAIN  ################
 
+# get device and developer password from optional env vars
+dev=$EZAPP_DEVICE
+password=$EZAPP_PASSWD
+
 # process options 
 # -h             : display usage
 # -d <dev>       : dev name (such as from /etc/hosts), or dev ipaddr
@@ -52,9 +56,15 @@ while true; do
     fi
 done
 
+# verify dev and password have been provided,
+# either from env vars or the -d and -p options
+if [ "$dev" = "" -o "$password" = "" ]; then
+    echo "ERROR: device and password are required"
+    exit 1
+fi
+
 # no additional args are allowed by ezget
 if [ $# -ne 0 ]; then
-    echo "ERROR: Ezget only supports copying files to the current directory."
     echo "ERROR: Args are not allowed."
     exit 1
 fi
@@ -80,17 +90,6 @@ fi
 android_dir=$(realpath --relative-base $files_dir $PWD)
 if [ "$android_dir" = "" ]; then
     echo "ERROR: failed to determine android_dir"
-    exit 1
-fi
-
-# get device and developer password from optional env vars
-dev=$EZAPP_DEVICE
-password=$EZAPP_PASSWD
-
-# verify dev and password have been provided,
-# either from env vars or the -d and -p options
-if [ "$dev" = "" -o "$password" = "" ]; then
-    echo "ERROR: device and password are required"
     exit 1
 fi
 
